export const SHOW_ABOUT_MODAL = "SHOW_ABOUT_MODAL";
export const HIDE_ABOUT_MODAL = "HIDE_ABOUT_MODAL";

export const SHOW_SETTING_MODAL = "SHOW_SETTING_MODAL";
export const HIDE_SETTING_MODAL = "HIDE_SETTING_MODAL";

export const LOAD_USER_SETTING = "LOAD_USER_SETTING";
export const USER_SETTING_UPDATE_MODE = "USER_SETTING_UPDATE_MODE";
export const USER_SETTING_TOGGLE_LAYOUT = "USER_SETTING_TOGGLE_LAYOUT";
export const EXPAND_WHOLE_TREE = "EXPAND_WHOLE_TREE";

export const USER_SETTING_UPDATE = "USER_SETTING_UPDATE";
export const USER_SETTING_UPDATE_SUCCESS = "USER_SETTING_UPDATE_SUCCESS";
export const CHANGE_URL = 'CHANGE_URL';
export const SELECT_NODE = "SELECT_NODE";
export const COLLAPSE_WHOLE_TREE = 'COLLAPSE_WHOLE_TREE';
export const EDIT_STUB_MODAL = "EDIT_STUB_MODAL";
export const EDIT_STUB = "EDIT_STUB";
export const EDIT_STUB_SUCCESS = "EDIT_STUB_SUCCESS";

export const CREATE_STUB = "CREATE_STUB";
export const HIDE_EDIT_STUB_MODAL = "HIDE_EDIT_STUB_MODAL";
export const HIDE_CREATE_STUB = "HIDE_CREATE_STUB";
export const DELETE_STUB = "DELETE_STUB";
export const DELETE_STUB_SUCCESS = 'DELETE_STUB_SUCCESS';
export const DUPLICATE_STUB = "DUPLICATE_STUB";
export const DISABLE_STUB = "DISABLE_STUB";
export const ENABLE_STUB = "ENABLE_STUB";
export const SHARE_STUB = "SHARE_STUB";
export const HIDE_SHARE_STUB = "HIDE_SHARE_STUB";
export const IMPORT_STUB = "IMPORT_STUB";
export const IMPORT_STUB_SUCCESS = "IMPORT_STUB_SUCCESS";
export const SHOW_CONTEXT_MODAL = "SHOW_CONTEXT_MODAL";
export const HIDE_CONTEXT_MODAL = "HIDE_CONTEXT_MODAL";

export const SHARE_GROUP_STUB = "SHARE_GROUP_STUB";
export const HIDE_SHARE_GROUP_STUB = "HIDE_SHARE_GROUP_STUB";
export const SHARE_GROUP = "SHARE_GROUP";

export const EXPORT_STUB = "EXPORT_STUB";
export const EXPORT_GROUP_STUB = "EXPORT_GROUP_STUB";
export const UPLOAD_STUB = "UPLOAD_STUB";
export const HIDE_UPLOAD_STUB = "HIDE_UPLOAD_STUB";

export const RESET_MAPPING = "RESET_MAPPING";
export const LOAD_ALL_MAPPINGS = "LOAD_ALL_MAPPINGS";
export const LOAD_ALL_MAPPINGS_SUCCESS = "LOAD_ALL_MAPPINGS_SUCCESS";
export const LOAD_NODES_SUCCESS = "LOAD_NODES_SUCCESS";
export const LOAD_SUGGESTED_ITEMS = "LOAD_SUGGESTED_ITEMS";
export const LOAD_SUGGESTED_ITEMS_SUCCESS = "LOAD_SUGGESTED_ITEMS_SUCCESS";

export const LOAD_GROUP_NAME = "LOAD_GROUP_NAME";
export const LOAD_GROUP_NAME_SUCCESS = "LOAD_GROUP_NAME_SUCCESS";
export const TOGGLE_NODE = "TOGGLE_NODE";
export const TOGGLE_NODE_BY_ID = "TOGGLE_NODE_BY_ID";

export const DEACTIVE_NODE = "DEACTIVE_NODE";
export const ADD_NEW_CONTEXT = "ADD_NEW_CONTEXT";
export const ADD_NEW_CONTEXT_SUCCESS = "ADD_NEW_CONTEXT_SUCCESS";

export const BACK_TO_DEFAULT_CONTEXT = "BACK_TO_DEFAULT_CONTEXT";
export const SWITCH_TO_NEW_CONTEXT = "SWITCH_TO_NEW_CONTEXT";

export const SAVE_STUB_SUCCESS = "SAVE_STUB_SUCCESS";

export const CREATE_NEW_STUB = "CREATE_NEW_STUB";
export const CREATE_NEW_STUB_SUCCESS = "CREATE_NEW_STUB_SUCCESS";
export const ADD_NEW_NODE_TO_TREE = "ADD_NEW_NODE_TO_TREE";




